title: EDP
description: POSISI MODEM CADANGAN
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

toc:
  ordered_list: true
  list_class: my-list-class
  sublist_class: my-sublist-class
.my-list-class {
  list-style-type: upper-alpha;
}

.my-sublist-class: {
  list-style-type: lower-alpha;
}
