defaults:
theme: jekyll-theme-architect
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "my-site"
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "default" # overrides previous default layout
      author: "gand0r"

